version: '3'
services:
  server:
    build: ./packages/server
    container_name: tab-edr-server
    ports:
      - "3000:3000"
    volumes:
      - './packages/server:/usr/src/app'
      - '/usr/src/app/node_modules'
    depends_on:
      - mongodb
    environment:
      - PORT=3000
    command: npm run dev

  webapp:
    build: ./packages/webapp
    container_name: tab-edr-webapp
    ports:
      - "4000:4000"
    volumes:
      - './packages/webapp:/usr/src/app'
      - '/usr/src/app/node_modules'
    depends_on:
      - server
    environment:
      - PORT=4000
      - NODE_ENV=development
    command: npm start

  # https://github.com/denisolek/docker-node-mongo-react-STARTER
  # public:
  #   image: nginx
  #   ports:
  #       - "8080:8080"
  #   volumes:
  #       - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  #       - ./frontend/dist:/usr/share/nginx/html

  mongodb:
    image: mongo
    container_name: tab-edr-mongo
    ports:
        - "27017:27017"