version: '3'
services:
  server:
    build: ./packages/server
    container_name: tab-edr-server
    ports:
      - "3000:3000"
    # depends_on:
    #   - mongodb
    command: npm run dev

  webapp:
    build: ./packages/webapp
    container_name: tab-edr-webapp
    ports:
      - "4000:4000"
    depends_on:
      - server
    command: npm run dev

  # https://github.com/denisolek/docker-node-mongo-react-STARTER
  # public:
  #   image: nginx
  #   ports:
  #       - "8080:8080"
  #   volumes:
  #       - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  #       - ./frontend/dist:/usr/share/nginx/html

  # mongodb:
  #   image: mongo
  #   ports:
  #       - "27017:27017"